version: '3.7'

services:
   revproxy:
     container_name: nginx
     image: custom-nginx
     build: ./
     depends_on:
       - server1
       - server2
       - server3
     restart: always
     ports:
       - 8080:8080
     networks:
      - mynet

   server1:
     container_name: server1
     image: myserver1
     build: ./servers/server1
     ports:
       - "1111:2323"
     restart: always
     networks:
      - mynet
   
   server2:
     container_name: server2
     image: myserver2
     build: ./servers/server2
     ports:
       - "2222:2323"
     restart: always
     networks:
      - mynet

   server3:
     container_name: server3
     image: myserver3
     build: ./servers/server3
     ports:
       - "3333:2323"
     restart: always
     networks:
      - mynet

networks:
    mynet:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
            gateway: 10.5.0.1